### ISSUE TITLE
How to add other sources to pull home value from?

### ISSUE THREAD

**Issue by SamAtwell** [mikepqr/real-estate-scrape#4]
Hey, 

I am interested in modifying this script to pull the home value from a few additional sites but I am unsure of how to add new sites. 

I see that the '__init__.py' file has the XPath information for Zillow and Redfin. So it just a matter of adding the XPath information for new sites I want to use to this file?

These are the sites I want to use, if you want to add one to show me:

https://www.rockethomes.com/how-much-is-my-home-worth

https://homevaluerealestatecenter.bankofamerica.com/

https://www.chase.com/personal/mortgage/calculators-resources/home-value-estimator

https://www.opendoor.com/w/home-value

https://www.pennymac.com/home-value-estimator

**Comment by mikepqr** [comment]
You have the right idea, but the scraping architecture is very simple (and limited).

The home's value needs to posted at a unique static URL. It doesn't work with forms, which rules out Opendoor, Chase and BofA. Penny Mac's valuation page has a session ID in the URL, so also won't work.

Based on a quick look, you might be able to get it to work with Rocket Homes. As you say, the trick is to add the Rocket Homes xpath to the sites dictionary in `__init__.py`, and then `ROCKETHOMES_URL` to your environment.

I'm going to close this issue, but If you figure it out then let me know and I'll add support for that site so other people can benefit from your work.

**Comment by SamAtwell** [comment]
Makes sense. I'll give that a try and let you know if it works.

Another question, if you don't mind - how would you recommend handling multiple addresses? A separate repo? Or is there a simpler solution?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mikepqr** [comment]
You can certainly create multiple repos. That's the easiest option in some ways.

The other option is to take advantage of the mapping from `FOO_URL` (in the environment) to foo's xpath in the `sites` dictionary, to "foo" (the column in the CSV file and label on the chart). foo can be anything you want.

So to have multiple addresss you could choose unique foo for each address+site combination. e.g. REDFIN1_URL=http://www.redfin.com/123mainstreet, and add "redfin1" to the sites dictionary. REDFIN2_URL=http://www.redfin.com/456broadway, and add "redfin2" to the sites dictionary (the xpath should be the same as redfin1).

This is obviously not super user-friendly, but the current design is all I personally needed so I didn't spend time improving that.

**Comment by SamAtwell** [comment]
Yea, I figured that would be the alternate but then all the data would be lumped together in one file/chart which would make it a little convoluted. I was trying to see if there is a way to spit out different files per address but I can go with separate repos for now.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
